# Generated by Django 5.2.6 on 2025-10-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
