# Generated by Django 5.2.7 on 2025-11-03 18:06

import cloudinary_storage.storage
import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmedia_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='media_file',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='image_file',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='post_media/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=posts.models.VideoCloudinaryStorage(), upload_to='post_media/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])]),
        ),
    ]
