# Generated by Django 5.2.7 on 2025-11-03 19:27

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_postmedia_media_file_postmedia_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='video_file',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, storage=posts.models.SmartCloudinaryStorage(), upload_to='post_media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])]),
        ),
    ]
