version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-reddit_clone}
      POSTGRES_USER: ${POSTGRES_USER:-reddit_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-please_set_password_in_env}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-reddit_user} -d ${POSTGRES_DB:-reddit_clone}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://reddit_user:${POSTGRES_PASSWORD}@postgres:5432/reddit_clone
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data: